version: '3.12.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
